### ISSUE TITLE
missing version tags

### ISSUE THREAD

**Issue by rofl0r** [janstarke/rexgen#61]
the latest tagged version is 2.0.6, yet it seems there have been many version bumps since.

**Comment by magnumripper** [comment]
+1

We're soon releasing a version of John the Ripper Jumbo and in the build instructions we state the last known good version of librexgen (for building with JtR) to be **2.0.8** [simply because that was what I happened to have installed and it works for me].

**Comment by teeshop** [comment]
I now require a higher version of flex and bison, which might be a problem on a lot of Linux System. Unfortunately I'm on the road these days and not being able to brute-force the least usable versions :-( So, I'd like to leave this issue open until I was able to test this on current Linux versions

**Comment by rofl0r** [comment]
opening this issue had 2 purposes

- remind me you to keep making tags
- retroactively create tags for previous releases

it seems only the former was achieved :/

**Comment by janstarke** [comment]
I did not have a clean release process in the past. I sometimes created a release and forgot to change the version number in the code, just to name an example.

So, it would be misleading to create version tags for older versions which haven't be *release*d properly. This is the reason why I'm not happy with the idea...
