### ISSUE TITLE
Architecture documentation link broken

### ISSUE THREAD

**Issue by gsauthof** [janstarke/rexgen#69]
The README.md currently reads:

> If you are interested in contributing, please have a look at the (Architecture Documentation)[doc/architecture.md]

I can't find the referenced file `architecture.md` anywhere in the repository.

Can you add it?

**Comment by janstarke** [comment]
I added some first architecture information.

Are there some special topics your are interested in?

**Comment by gsauthof** [comment]
> I added some first architecture information.

Thanks.

> Are there some special topics your are interested in?

I'm mainly interested in the used algorithmic approach to the generation of regular expressions.

From the added document I gather that the code works on an AST, i.e. the iterators are called top-down recursively on the  AST nodes.

**Comment by janstarke** [comment]
That's exactly how it is working
